
exec_env: "spark"

logdir: ../../var/log/
logfile: log
node_logfile: node_log
loglevel: DEBUG

rotate_log_size: 268435456 #1024*1024*256B
#rotate_log_size: 1073741824 #1024*1024*1024B
#rotate_log_size: 1048576 #1024*1024B
#rotate_log_size: 1000 #1024*1024B
rotate_log_lines: 100000
backup_log_count: 10

myslq_url: "mysql+pymysql://alladmin:admin@localhost/mnist?charset=utf8"
wikitext_myslq_url: "mysql+pymysql://alladmin:admin@localhost/wikitext?charset=utf8"

